# %%
import matplotlib.pyplot as plt
import anndata
import scanpy as sc
import snapatac2 as snap
import numpy as np
import pandas as pd
import os
import scanpy.external as sce
import argparse
#adata_concat = snap.read_dataset('output/mouse_brain.h5ads')

parser = argparse.ArgumentParser(description="Calculate the methlyation level for a given region")
parser.add_argument("--input", type=str, required=False, help="Input file for the h5ad generated by snapATAC2",
                    default="/data2st1/junyi/output/mouse_brain_dar.h5ad")
parser.add_argument("--output", type=str, required=False, help="Output path of the methylation level",
                    default="/data2st1/junyi/output/motif/")
#parser.add_argument("--celltype", type=str, required=False, help="Select cell type in obs",default="Neuron")
parser.add_argument("--region", type=str, required=False, help="Brain region",default="PFC")
parser.add_argument("--celltype_column", type=str, required=False, help="Sample name",default="celltype.L2")


args = parser.parse_args()

# %%
file = args.input
region = args.region
#celltype = args.celltype
celltype_column = args.celltype_column
adata = anndata.read_h5ad(file)
for celltype in adata.obs[celltype_column].unique():
    adata_AMY_neuron = adata[(adata.obs['sample'].str.contains(region)) & (adata.obs['celltype_column'].str.contains(celltype))].copy()
    peak_mat=adata_AMY_neuron
    sc.tl.rank_genes_groups(peak_mat, groupby='expriment', method='wilcoxon',pts=True)
    df = sc.get.rank_genes_groups_df(peak_mat, group='MC', key='rank_genes_groups',pval_cutoff=0.05,log2fc_min=0)
    base_name = f"{region}_{celltype}"
    base_name = base_name.replace(" ","_")
    base_name = base_name.replace("/","-")
    df.to_csv(f"{args.output}/{base_name}_MC_wilcoxon.csv")
    df_mw = sc.get.rank_genes_groups_df(peak_mat, group='MW', key='rank_genes_groups',pval_cutoff=0.05,log2fc_min=0)
    df_mw.to_csv(f"{args.output}/{base_name}_MW_wilcoxon.csv")