# %%
import matplotlib.pyplot as plt
import anndata
import scanpy as sc
import snapatac2 as snap
import numpy as np
import pandas as pd
import os
import scanpy.external as sce
import argparse
import memento
from sklearn.preprocessing import LabelEncoder
#adata_concat = snap.read_dataset('output/mouse_brain.h5ads')

parser = argparse.ArgumentParser(description="Calculate the methlyation level for a given region")
parser.add_argument("--input", type=str, required=False, help="Input file for the h5ad generated by snapATAC2",
                    default="/data2st1/junyi/output/atac0416/3REGIONS_peak.h5ads")
parser.add_argument("--output", type=str, required=False, help="Output path of the result",
                    default="/data2st1/junyi/output/motif/")
#parser.add_argument("--celltype", type=str, required=False, help="Select cell type in obs",default="Neuron")
parser.add_argument("--region", type=str, required=False, help="Brain region",default="PFC")
parser.add_argument("--celltype_column", type=str, required=False, help="Column for cell type",default="region_nt")
parser.add_argument("--method", type=str, required=False, help="Method for analysis",default="memento-binary")
parser.add_argument("--cpu", type=int, required=False, help="Number of CPUs",default=32)


args = parser.parse_args()

# %%
file = args.input
region = args.region
#celltype = args.celltype
celltype_column = args.celltype_column
adata = anndata.read_h5ad(file)
adata = adata[(adata.obs['sample'].str.contains(region))]

outfolder = os.path.join(args.output,celltype_column)
if not os.path.exists(outfolder):
    os.makedirs(outfolder)
for celltype in adata.obs[celltype_column].unique():
    try:
        print(f"Processing {celltype}")
        adata_subset = adata[adata.obs[celltype_column].str.contains(celltype)]
        base_name = f"{region}_{celltype}"
        base_name = base_name.replace(" ","_")
        base_name = base_name.replace("/","-")

        if args.method == "wilcoxon":
            sc.tl.rank_genes_groups(adata_subset, groupby='expriment', method='wilcoxon',pts=True)
            df = sc.get.rank_genes_groups_df(adata_subset, group='MC', key='rank_genes_groups',pval_cutoff=0.05,log2fc_min=0)
            df.to_csv(f"{outfolder}/{base_name}_MC_wilcoxon.csv")
            df_mw = sc.get.rank_genes_groups_df(adata_subset, group='MW', key='rank_genes_groups',pval_cutoff=0.05,log2fc_min=0)
            df_mw.to_csv(f"{outfolder}/{base_name}_MW_wilcoxon.csv")
        elif args.method == "memento-binary":
            adata_subset.layers['normalized'] = adata_subset.X.copy()
            adata_subset.X =adata_subset.layers['count']
            adata_subset.obs['stim'] = adata_subset.obs['expriment'].apply(lambda x: 0 if x == 'MW' else 1)
            result_1d = memento.binary_test_1d(
                adata=adata_subset, 
                capture_rate=0.07, 
                treatment_col='stim', 
                num_cpus=args.cpu,
                num_boot=5000)
            df_mc = result_1d.query('de_coef > 0 & de_pval < 0.05').sort_values('de_pval')
            df_mc.to_csv(f"{outfolder}/{base_name}_MC_mementob.csv")
            df_mw = result_1d.query('de_coef < 0 & de_pval < 0.05').sort_values('de_pval')
            df_mw.to_csv(f"{outfolder}/{base_name}_MW_mementob.csv")    

    except Exception as e:
        print(f"Error processing {celltype}: {e}")
        continue