# %%
import matplotlib.pyplot as plt
import anndata
import scanpy as sc
import numpy as np
import pandas as pd
import os
import scanpy.external as sce
import argparse
import loompy as lp
#adata_concat = snap.read_dataset('output/mouse_brain.h5ads')

parser = argparse.ArgumentParser(description="Calculate the methlyation level for a given region")
parser.add_argument("--input", type=str, required=False, help="Input file for the h5ad generated by snapATAC2",
                    default="/data2st2/junyi/output/stg1028/")
parser.add_argument("--output", type=str, required=False, help="Output path of the result",
                    default="/data2st2/junyi/output/stg1028/subsetsn/")
#parser.add_argument("--celltype", type=str, required=False, help="Select cell type in obs",default="Neuron")
parser.add_argument("--region", type=str, required=False, help="Brain region",default="PFC")
parser.add_argument("--celltype_column", type=str, required=False, help="Column for cell type",default="celltype.L2")
parser.add_argument("--method", type=str, required=False, help="Method for analysis",default="memento-ht")
parser.add_argument("--cpu", type=int, required=False, help="Number of CPUs",default=32)
parser.add_argument("--cov_column", type=str, required=False, help="Covariate column in the adata.obs",default="farcq")
parser.add_argument("--capture_rate", type=float, required=False, help="Capture rate for the region",default=0.15)


args = parser.parse_args()

# %%
folder = args.input
region = args.region
#celltype = args.celltype
celltype_column = args.celltype_column

covariate_column = args.cov_column
adata_CSRES = anndata.read_h5ad(os.path.join(folder,'CSRES_4VN','CSRES_4VN.h5ad'))
adata_CURES = anndata.read_h5ad(os.path.join(folder,'CURES_4VN','CURES_4VN.h5ad'))
adata_CUMS = anndata.read_h5ad(os.path.join(folder,'CUMS_4VN','CUMS_4VN.h5ad'))
adata_CSDS = anndata.read_h5ad(os.path.join(folder,'CSDS_4VN','CSDS_4VN.h5ad'))
adata_CSDS = adata_CSDS[adata_CSDS.obs['status']=='CSDS']
adata_CSRES = adata_CSRES[adata_CSRES.obs['status']=='CSRES']
adata_CURES = adata_CURES[adata_CURES.obs['status']=='CURES']
adata = adata_CUMS.concatenate([adata_CSDS, adata_CSRES, adata_CURES])
adata.obs['celltype.L2.region.sex'] = adata.obs['region'].astype(str) + "_"+adata.obs['celltype.L2'].astype(str) + "_" + adata.obs['sex'].astype(str)
adata.obs['celltype.L2.region.sex'] = adata.obs['celltype.L2.region.sex'].str.replace('/','-')
adata.obs['celltype.L2.region.sex'] = adata.obs['celltype.L2.region.sex'].str.replace(' ','_')

for celltype in adata.obs['celltype.L2.region.sex'].unique():

    try:
        print(f"Processing {celltype}")

        adata_subset = adata[adata.obs['celltype.L2.region.sex']==celltype]

        row_attrs = {
        "Gene": np.array(adata_subset.var_names) ,
        }
        col_attrs = {
            "CellID": np.array(adata_subset.obs_names) ,
            "nGene": np.array( np.sum(adata_subset.X.transpose()>0 , axis=0)).flatten() ,
            "nUMI": np.array( np.sum(adata_subset.X.transpose() , axis=0)).flatten() ,
        }

        base_name = f"{celltype}"
        base_name = base_name.replace(" ","_")
        base_name = base_name.replace("/","-")
        if os.path.exists(os.path.join(args.output, f"{base_name}.loom")):
            print(f"File {base_name}.loom already exists, skipping.")
            continue
        else:
            lp.create( os.path.join(args.output, f"{base_name}.loom"), adata_subset.X.transpose(), row_attrs, col_attrs)

    except Exception as e:
        print(f"Error processing {celltype}: {e}")
        continue
# %%

