# %%
import matplotlib.pyplot as plt
import anndata
import scanpy as sc
import numpy as np
import pandas as pd
import os
import scanpy.external as sce
import argparse
import loompy as lp
#adata_concat = snap.read_dataset('output/mouse_brain.h5ads')

parser = argparse.ArgumentParser(description="Calculate the methlyation level for a given region")
parser.add_argument("--input", type=str, required=False, help="Input file for the h5ad generated by snapATAC2",
                    default="/data2st2/junyi/output/stg1028/")
parser.add_argument("--output", type=str, required=False, help="Output path of the result",
                    default="/data2st2/junyi/output/stg1028/allsn/")
#parser.add_argument("--celltype", type=str, required=False, help="Select cell type in obs",default="Neuron")
parser.add_argument("--region", type=str, required=False, help="Brain region",default="PFC")
parser.add_argument("--celltype_column", type=str, required=False, help="Column for cell type",default="celltype.L2")
parser.add_argument("--method", type=str, required=False, help="Method for analysis",default="memento-ht")
parser.add_argument("--cpu", type=int, required=False, help="Number of CPUs",default=32)
parser.add_argument("--cov_column", type=str, required=False, help="Covariate column in the adata.obs",default="farcq")
parser.add_argument("--capture_rate", type=float, required=False, help="Capture rate for the region",default=0.15)


args = parser.parse_args()

# %%
folder = args.input
region = args.region
#celltype = args.celltype
celltype_column = args.celltype_column

covariate_column = args.cov_column
dataset_configs = [
    ("CSRES", os.path.join(folder, 'CSRES_4VN', 'CSRES_4VN.h5ad'), 'CSRES'),
    ("CURES", os.path.join(folder, 'CURES_4VN', 'CURES_4VN.h5ad'), 'RES'),
    ("CUMS", os.path.join(folder, 'CUMS_4VN', 'CUMS_4VN.h5ad'), None),
    ("CSDS", os.path.join(folder, 'CSDS_4VN', 'CSDS_4VN.h5ad'), 'CSDS'),
]


def build_celltype_region(obs_frame):
    celltype_region = obs_frame['region'].astype(str) + "_" + obs_frame[celltype_column].astype(str)
    celltype_region = celltype_region.str.replace('/', '-', regex=False)
    return celltype_region.str.replace(' ', '_', regex=False)


datasets = []
all_celltypes = set()

for dataset_name, dataset_path, status_value in dataset_configs:
    adata_backed = anndata.read_h5ad(dataset_path, backed='r')
    obs_frame = adata_backed.obs.copy()
    if status_value is not None:
        obs_frame = obs_frame[obs_frame['status'] == status_value].copy()
    obs_frame['celltype.L2.region'] = build_celltype_region(obs_frame)
    all_celltypes.update(obs_frame['celltype.L2.region'].unique())
    datasets.append((dataset_name, adata_backed, obs_frame))

for celltype in sorted(all_celltypes):

    try:
        print(f"Processing {celltype}")

        subset_list = []
        for dataset_name, adata_backed, obs_frame in datasets:
            selected_obs = obs_frame[obs_frame['celltype.L2.region'] == celltype]
            if selected_obs.empty:
                continue
            adata_subset = adata_backed[selected_obs.index, :].to_memory()
            adata_subset.obs = selected_obs.copy()
            subset_list.append(adata_subset)

        if not subset_list:
            print(f"No cells found for {celltype}, skipping.")
            continue

        if len(subset_list) == 1:
            adata_subset = subset_list[0]
        else:
            adata_subset = anndata.concat(subset_list, join='inner', merge='same')

        row_attrs = {
        "Gene": np.array(adata_subset.var_names) ,
        }
        col_attrs = {
            "CellID": np.array(adata_subset.obs_names) ,
            "nGene": np.array( np.sum(adata_subset.X.transpose()>0 , axis=0)).flatten() ,
            "nUMI": np.array( np.sum(adata_subset.X.transpose() , axis=0)).flatten() ,
        }

        base_name = f"{celltype}"
        base_name = base_name.replace(" ","_")
        base_name = base_name.replace("/","-")
        if os.path.exists(os.path.join(args.output, f"{base_name}.loom")):
            print(f"File {base_name}.loom already exists, skipping.")
            continue
        else:
            lp.create( os.path.join(args.output, f"{base_name}.loom"), adata_subset.X.transpose(), row_attrs, col_attrs)

    except Exception as e:
        print(f"Error processing {celltype}: {e}")
        continue

for _, adata_backed, _ in datasets:
    adata_backed.file.close()
# %%

